spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  deserialization:
    fail-on-unknown-properties: false

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: 'health,info'

server:
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json
    excluded-user-agents: 'gozilla,traviata'
  ssl:
    enabled: false
    key-alias: tomcat
    key-store: '${user.home}/.keystore'
    key-store-password: changeit
    key-password: changeit
    protocol: TLS
    enabled-protocols: TLSv1+TLSv1.1+TLSv1.2

logging:
  level:
    org.zalando.logbook: INFO